// Country code to flag emoji mapping
// Using ISO 3166-1 alpha-2 country codes
export const countryFlags: Record<string, string> = {
  'Iran': '🇮🇷',
  'France': '🇫🇷',
  'Japan': '🇯🇵',
  'United States': '🇺🇸',
  'USA': '🇺🇸',
  'United Kingdom': '🇬🇧',
  'UK': '🇬🇧',
  'Germany': '🇩🇪',
  'Italy': '🇮🇹',
  'Spain': '🇪🇸',
  'Canada': '🇨🇦',
  'Australia': '🇦🇺',
  'China': '🇨🇳',
  'India': '🇮🇳',
  'Brazil': '🇧🇷',
  'Mexico': '🇲🇽',
  'Turkey': '🇹🇷',
  'Egypt': '🇪🇬',
  'South Africa': '🇿🇦',
  'Argentina': '🇦🇷',
  'Chile': '🇨🇱',
  'Peru': '🇵🇪',
  'Colombia': '🇨🇴',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'Indonesia': '🇮🇩',
  'Philippines': '🇵🇭',
  'South Korea': '🇰🇷',
  'New Zealand': '🇳🇿',
  'Greece': '🇬🇷',
  'Portugal': '🇵🇹',
  'Netherlands': '🇳🇱',
  'Belgium': '🇧🇪',
  'Switzerland': '🇨🇭',
  'Austria': '🇦🇹',
  'Poland': '🇵🇱',
  'Czech Republic': '🇨🇿',
  'Hungary': '🇭🇺',
  'Sweden': '🇸🇪',
  'Norway': '🇳🇴',
  'Denmark': '🇩🇰',
  'Finland': '🇫🇮',
  'Ireland': '🇮🇪',
  'Russia': '🇷🇺',
  'Saudi Arabia': '🇸🇦',
  'UAE': '🇦🇪',
  'United Arab Emirates': '🇦🇪',
  'Qatar': '🇶🇦',
  'Kuwait': '🇰🇼',
  'Oman': '🇴🇲',
  'Bahrain': '🇧🇭',
  'Jordan': '🇯🇴',
  'Lebanon': '🇱🇧',
  'Iraq': '🇮🇶',
  'Afghanistan': '🇦🇫',
  'Pakistan': '🇵🇰',
  'Bangladesh': '🇧🇩',
  'Sri Lanka': '🇱🇰',
  'Nepal': '🇳🇵',
  'Myanmar': '🇲🇲',
  'Malaysia': '🇲🇾',
  'Singapore': '🇸🇬',
  'Cambodia': '🇰🇭',
  'Laos': '🇱🇦',
  'Mongolia': '🇲🇳',
  'North Korea': '🇰🇵',
  'Taiwan': '🇹🇼',
  'Hong Kong': '🇭🇰',
  'Macau': '🇲🇴'
};

export function getCountryFlag(country: string): string {
  return countryFlags[country] || '🌍';
}
